#!/bin/bash

# Welcome to the Nimble laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -e

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

pre_setup() {
  if [ ! -d "$HOME/.bin/" ]; then
    mkdir "$HOME/.bin"
  fi

  if [ ! -f "$HOME/.zshrc" ]; then
    touch "$HOME/.zshrc"
  fi

  if [ ! -f "$HOME/.Brewfile" ]; then
    touch "$HOME/.Brewfile"
  fi

  # shellcheck disable=SC2016
  append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

  # Determine Homebrew prefix
  ARCH="$(uname -m)"
  if [ "$ARCH" = "arm64" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
  else
    HOMEBREW_PREFIX="/usr/local"
  fi
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$zshrc"
    else
      printf "\n%s\n" "$text" >> "$zshrc"
    fi
  fi
}

prepend_to_zshrc() {
  local text="$1" zshrc

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  echo -e "$text\n\n$(cat $zshrc)" > $zshrc
}

config_zsh() {
  read -r -p "Do you want to install Zsh's extensions? [Y|n] " response

  if [[ ! $response =~ (n|no|N) ]];then
    sudo chsh -s $(which zsh)

    fancy_echo "Installing Oh my Zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended

    if [ ! -d ~/.zsh/zsh-defer ]; then
      git clone https://github.com/romkatv/zsh-defer.git ~/.zsh/zsh-defer
      prepend_to_zshrc 'source ~/.zsh/zsh-defer/zsh-defer.plugin.zsh'
    fi
    if [ ! -d ~/.zsh/zsh-autosuggestions ]; then
      git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.zsh/zsh-autosuggestions
      prepend_to_zshrc 'source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh'
    fi
    if [ ! -d ~/.zsh/zsh-syntax-highlighting ]; then
      git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
      prepend_to_zshrc 'source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
    fi
    if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-completions ]; then
      git clone https://github.com/zsh-users/zsh-completions.git ~/.oh-my-zsh/custom/plugins/zsh-completions
      prepend_to_zshrc 'fpath+=~/.oh-my-zsh/custom/plugins/zsh-completions/src'
    fi

    prepend_to_zshrc 'ZSH_DISABLE_COMPFIX=true'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

    zsh_config_homebrew

    fancy_echo "Configured Zsh"
  fi
}

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

install_homebrew() {
  if ! command -v brew >/dev/null; then
    fancy_echo "Installing Homebrew ..."
      /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      zsh_config_homebrew

      export PATH="$HOMEBREW_PREFIX/bin:$PATH"
  fi

  if brew list | grep -Fq brew-cask; then
    fancy_echo "Uninstalling old Homebrew-Cask ..."
    brew uninstall --force brew-cask
  fi
}

zsh_config_homebrew() {
  fancy_echo "Adding brew to zshrc automatically..."
  append_to_zshrc "eval \"\$($HOMEBREW_PREFIX/bin/brew shellenv)\""
}

append_general_dependencies() {
  fancy_echo "Appending general dependencies to Brewfile"

  tee "$HOME/.Brewfile" <<-EOF
    # General
    tap "thoughtbot/formulae"
    tap "homebrew/services"
    tap "github/gh"

    # mas-cli to install macOS apps
    brew "mas"

    # General apps
    cask "slack" unless File.directory?("/Applications/Slack.app")
    cask "google-chrome" unless File.directory?("/Applications/Google Chrome.app")
    cask "iterm2" unless File.directory?("/Applications/iTerm.app")
    
    #Developer apps
    cask "visual-studio-code" unless File.directory?("/Applications/Visual Studio Code.app")
    cask "insomnia" unless File.directory?("/Applications/Insomnia.app")

    # Unix
    brew "git"
    brew "openssl"
    brew "zsh"
    brew "tree"

    # GitHub extensions
    brew "gh"

    # Programming language prerequisites and package managers
    brew "libyaml" # should come after openssl
    brew "coreutils"
EOF
}

append_web_dependencies() {
  fancy_echo "Appending web's dependencies to Brewfile"

  tee -a "$HOME/.Brewfile" <<-EOF
    # Languages
    brew "node"

    # Devops
    cask "docker"
    brew "awscli"

    # Others
    brew "nvm"
    brew "yarn"
    cask "jetbrains-toolbox"
EOF
}

install_dependencies() {
  fancy_echo "Updating Homebrew formulae ..."
  brew update --force # https://github.com/Homebrew/brew/issues/1151

  fancy_echo "Installing dependencies"
  brew bundle --global --verbose --no-upgrade

  fancy_echo "Installed dependencies"
}

install_laptop_local() {
  if [ -f "$HOME/.laptop.local" ]; then
    fancy_echo "Running your customizations from ~/.laptop.local ..."
    # shellcheck disable=SC1090
    . "$HOME/.laptop.local"
  fi
}

config_git() {
  fancy_echo "Globally ignoring .DS_Store files"
  echo .DS_Store >> ~/.gitignore_global
  git config --global core.excludesfile ~/.gitignore_global
  git config --global init.defaultBranch main
}

config_vscode_extensions() {
  # Misc
  code --install-extension streetsidesoftware.code-spell-checker
  code --install-extension donjayamanne.githistory
  code --install-extension k--kato.intellij-idea-keybindings
  code --install-extension ms-vsliveshare.vsliveshare
  code --install-extension ms-vscode.makefile-tools
  code --install-extension bengreenier.vscode-node-readme
  code --install-extension christian-kohler.path-intellisense
  code --install-extension ms-vscode-remote.remote-ssh
  code --install-extension ms-vscode-remote.remote-ssh-edit
  code --install-extension ms-vscode.remote-explorer
  code --install-extension simonsiefke.svg-preview
  code --install-extension rangav.vscode-thunder-client
  code --install-extension ChakrounAnas.turbo-console-log
  code --install-extension chrmarti.regex
  code --install-extension shd101wyy.markdown-preview-enhanced
  code --install-extension SonarSource.sonarlint-vscode
  code --install-extension wk-j.vscode-httpie
  
  # Database
  code --install-extension cweijan.vscode-database-client2
  
  # Infra
  code --install-extension ms-azuretools.vscode-docker
  code --install-extension hashicorp.terraform
  
  # .NET
  code --install-extension ms-dotnettools.csharp
  code --install-extension formulahendry.dotnet-test-explorer
  code --install-extension davidpetersmke.mstestsnippets
  
  #Themes
  code --install-extension equinusocio.vsc-material-theme
  code --install-extension pkief.material-icon-theme
  code --install-extension emmanuelbeziat.vscode-great-icons
  
  # Web
  code --install-extension mgmcdermott.vscode-language-babel
  code --install-extension mikestead.dotenv
  code --install-extension dbaeumer.vscode-eslint
  code --install-extension heybourn.headwind
  code --install-extension bradlc.vscode-tailwindcss
  code --install-extension chrisbibby.hide-node-modules
  code --install-extension firsttris.vscode-jest-runner
  code --install-extension christian-kohler.npm-intellisense
  code --install-extension esbenp.prettier-vscode
  code --install-extension formulahendry.auto-rename-tag
  code --install-extension ms-vscode.vscode-typescript-next
}

install() {
  pre_setup
  install_homebrew

  append_general_dependencies

  append_web_dependencies
  
  install_dependencies

  install_laptop_local

  brew cleanup
}

# Check for Xcode Devtools and wait for them to be installed before continuing
xcode-select -p 2>/dev/null
return_code=$?

while [ $return_code -eq 2 ]
do
  fancy_echo "\033[1;31mApple's Xcode Developer Tools are not installed!\033[0m"
  fancy_echo "\033[1;31mPlease install them through the dialog box before continuing with running this installation script.\033[0m"
  fancy_echo "Many of the tools used in this script will not work without the Xcode developer tools"
  fancy_echo "Opening 'Install Command Line Developer Tools'"
  xcode-select --install 1>/dev/null
  fancy_echo "Press enter to try again once Xcode developer tools are installed"
  read input
  xcode-select -p
  return_code=$?
done

# Run
install

config_zsh

config_git

config_vscode_extensions

fancy_echo "Installation successful"
